Add helm chart
giantswarm/goldilocks-app pull request #18
Opened 2021-02-25 10:43 UTC by pipo02mix

Towards https://github.com/giantswarm/roadmap/issues/275

2021-02-25 11:22 UTC, yasn77 requested changes
The main thing is, that I don't think we need to ship VPA as a sub chart, just use what we already have

2021-02-25 11:22 UTC, yasn77 commented on helm/goldilocks-app/Chart.yaml
> +  repository: https://charts.fairwinds.com/stable
We have VPA in our catalogue, I think we should reference that
(https://github.com/giantswarm/giantswarm-playground-catalog/blob/master/vertical-pod-autoscaler-app-1.0.3.tgz)

2021-02-25 11:22 UTC, yasn77 commented on helm/goldilocks-app/charts/vpa/Chart.yaml
> +apiVersion: v2
Same as the previous comment, I don't think we need to ship it as a sub chart, we should just pull it in

2021-02-25 11:22 UTC, yasn77 commented on helm/goldilocks-app/values.yaml
> +  repository: quay.io/giantswarm/goldilocks
We have a pattern for images -> https://github.com/giantswarm/installations/blob/master/default/appcatalog/default-appcatalog-values.yaml#L21 

This ensures that China clusters use the right repo

2021-03-04 11:50 UTC, pipo02mix commented
can you review @yasn77 ?

2021-03-04 12:17 UTC, yasn77 approved these changes
Thanks for the updates @pipo02mix 

LGTM :shipit:

2021-03-04 12:27 UTC, ubergesundheit commented
Can you rename the jobs in the circle ci config file to include the catalog which they push to?

Then we can change the branch protection.

2021-03-04 13:58 UTC, merged